services:
  - type: web
    name: educonnect
    env: dotnet
    plan: free
    rootDir: ./
    buildCommand: dotnet build EduConnect.csproj
    startCommand: dotnet EduConnect.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
